### PR TITLE
Prepend to full PYTHONPATH

### PR DESCRIPTION
**Pull request by akorgor**

### CODE REVIEW

**Comment by terhorstd** [comment]
During the review please check if the module file `glob` works with both module systems, i.e. on the TCL-based legacy  `environment-modules`, and on HPC (usually using the Lua `lmod`).

**Comment by jhnnsnk** [comment]
@terhorstd Please reassign this PR to @JanVogelsang as a reviewer.

**Comment by JanVogelsang** [comment]
Shouldn't the `NEST_MODULE_PATH` be determined in the same way?
```sh
setenv          NEST_MODULE_PATH        \$INSTALLDIR/lib64/nest
```
-->
```sh
setenv          NEST_MODULE_PATH        [glob -directory \$INSTALLDIR/ -type d lib*/nest/]
```

**Review by JanVogelsang — CHANGES_REQUESTED** [review]
This one can be closed in favor of #61

**Comment by terhorstd** [comment]
Thanks, @JanVogelsang !

**Pull request closed without merging**
